name: Manually deploy image to GHCR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'dev'

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: datadreamer

jobs:
  push-store:
    name: Push the image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}  # Checkout the selected branch

      - name: 'Extract short commit hash'
        id: commit_hash
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: luxonis-ml
          password: ${{ secrets.GHCR_PAT }}

      - name: 'Build and Push Image to GHCR'
        run: |
          docker build --build-arg GITHUB_TOKEN=${{secrets.GHCR_PAT}} --build-arg BRANCH=${{ inputs.branch }} . \
            --tag ghcr.io/luxonis/datadreamer:${{ env.short_hash }}
          docker push ghcr.io/luxonis/datadreamer --all-tags
