name: Docker Build and Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/luxonis/datadreamer:latest
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GHCR_PAT }}
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
