name: Docker Build and Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: luxonis-ml
        password: ${{ secrets.GHCR_PAT }}

    - name: Publish
      run: |
        docker build -t ghcr.io/luxonis/datadreamer:latest .
        docker push ghcr.io/luxonis/datadreamer:latest
